yatube/api/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers

router = routers.DefaultRouter()
router.register('v1/posts', PostAPI)
router.register('v1/group', GroupAPI)
router.register(
    r'v1/posts/(?P<post_id>\d+)/comments',
    CommentAPI,
    basename='comment'
)
router.register('v1/follow', FollowAPI, basename='follow')

urlpatterns = [
    path('auth/', include('djoser.urls')),
    # JWT-эндпоинты, для управления JWT-токенами:
    path('auth/', include('djoser.urls.jwt')),
    path('', include(router.urls))
]

yatube/posts/urls.py
from tokenize import group
from django.urls import include, path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home_page'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path("search/", views.search, name="search"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='edit'),
    path('delite/<int:post_id>', views.delite_post, name='delite'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow, 
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
]

handler404 = 'core.views.pageNotFound'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),) 

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

# Create your models here.

User = get_user_model()

class Post(models.Model):
    text = models.TextField(verbose_name='Текст', help_text='Введите текст')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author',
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.CASCADE,
        related_name='group',
        blank=True, 
        null=True,
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    ) 

    def __str__(self) -> str:
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(verbose_name='Заголовок' ,max_length=200)
    slug = models.SlugField(verbose_name='URL адресс',max_length=200,)
    description = models.TextField(verbose_name='Описание')

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("group_list", kwargs={"slug": self.slug})


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    def __str__(self) -> str:
        return self.author.username

yatube/posts/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image',)

"""    def clean_group(self):
        data = self.cleaned_data['text']

        if data == '':
            raise forms.ValidationError('Это поле не должно быть пустым!')

        return data"""


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    template = 'posts/index.html'
    posts_list = (
        Post.objects.order_by('-pub_date')
        .select_related('group')
        .select_related('author')
    )
    paginator = Paginator(posts_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'req_user': request.user,
        'page_obj': page_obj,
    }
    return HttpResponse(render(request, template, context))


def search(request):
    keyword = request.GET.get("q", None)
    if keyword:
        posts = (
            Post.objects.filter(text__contains=keyword)
            .select_related('author')
            .select_related('group')
        )
    else:
        posts = None
    return render(request, "search.html", {"posts": posts, "keyword": keyword})


def group_post(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_list = (
        Post.objects.filter(group=group)
        .order_by('-pub_date')
        .select_related('group')
        .select_related('author')
    )
    paginator = Paginator(posts_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {
        'req_user': request.user,
        'group': group,
        'page_obj': page_obj,
    }
    return HttpResponse(render(request, template, context))


def profile(request, username):
    user_author = get_object_or_404(User, username=username)
    # posts = user_author.author.all() либо попробывать так
    posts = (
        Post.objects.select_related('group')
        .select_related('author')
        .filter(author_id=user_author.pk)
        .order_by('-pub_date')
    )
    #  проверим есть ли подписка пользователя на автора страницы
    following = Follow.objects.filter(user=request.user, author=user_author).exists()
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    post_count = posts.count()
    context = {
        'req_user': request.user,
        'user_author': user_author,
        'post_count': post_count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    if Post.objects.filter(pk=post_id).exists():
        post = (
            Post.objects
            .select_related('author')
            .select_related('group')
            .get(pk=post_id)
        )
        count_posts = Post.objects.filter(author_id=post.author.pk).count()
        comments = Comment.objects.filter(post=post_id)
        form = CommentForm()
        context = {
            'req_user': request.user,
            'post': post,
            'count': count_posts,
            'form': form,
            'comments': comments,
        }
        return render(request, 'posts/post_detail.html', context)
    raise Http404()


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES or None)
        if form.is_valid():
            complite = form.save(commit=False)
            complite.author = request.user
            complite.save()
            return redirect('posts:profile', username=request.user)
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


def post_edit(request, post_id):
    if Post.objects.filter(pk=post_id).exists():
        post = Post.objects.select_related('author').get(pk=post_id)
        if request.method == 'GET':
            is_edit = True
            if post.author == request.user:
                # вставить в форму пост для редактирования
                form = PostForm(
                    instance=post,
                    files=request.FILES or None
                ) 
                return render(request, 'posts/create_post.html', {'form': form, 'is_edit': is_edit, 'post_id': post_id})
            return redirect('/auth/login/')
        # instance переопределяет параметры которые не вошли в пост запрос, в коде ниже второй вариант передачи параметров
        form = PostForm(
            request.POST,
            instance=post,
            files=request.FILES or None
        )
        if form.is_valid():
            complite = form.save(commit=False)
            #complite.author = request.user 
            #complite.pk = post.pk
            #complite.pub_date = post.pub_date
            complite.save()
            return redirect('posts:profile', username=request.user)
        return render(request,'posts/create_post.html', {'form': form, 'is_edit': is_edit, 'post_id': post_id}, ) #пользователь переделывает форму, она не валид
    return Http404()


def delite_post(request, post_id): 
    try:
        post = Post.objects.select_related('author').get(pk=post_id)
        if post.author == request.user:
            post.delete()
    finally:
        return redirect('posts:home_page')


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def follow_index(request):
    try:
        authors = Follow.objects.filter(user=request.user)
        #  создадим пустой qweryset
        posts = Post.objects.none()
        #  в цикле объеденим его с множествами постов по подписанным авторам   
        for author in authors:
            QS = Post.objects.select_related('author').filter(author=author.author)
            posts = posts.union(QS)
        paginator = Paginator(posts.order_by('-pub_date'), 10)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'posts/follow.html', {'page_obj':page_obj})
    except:
        raise Http404()


@login_required
def profile_follow(request, username):
    try:
        follow_obj = Follow.objects.create(user=request.user, author=User.objects.get(username=username))
        follow_obj.save()
        return redirect('posts:profile', username=username)
    except:
        raise Http404()

@login_required
def profile_unfollow(request, username):
    try:
        follow_obj = Follow.objects.filter(user=request.user, author=User.objects.get(username=username))
        follow_obj.delete()
        return redirect('posts:profile', username=username)
    except:
        raise Http404()

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
{%if is_edit %}
  Редактировать пост
{% else %}
  Создать пост
{% endif %}
{% endblock %}
{% block contend %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          Новый пост             
        </div>
        <div class="card-body">
          {%if form.errors%}
            {% for field in form %} 
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %} 

          {% if is_edit %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:edit' post_id %}">
          {% else %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:create' %}"> 
          {% endif %}
          
            {% csrf_token %}
            {% for field in form %}         
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}   
                {% if field.field.required %}               
                  <span class="required text-danger" >*</span> 
                {% endif %}                 
              </label>
              {{ field|addclass:'form-control' }} 
              {% if field.help_text %}               
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}                  
            </div>
            {% endfor %}          
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
              {%if is_edit %}
                Редактировать
              {% else %}
                Сохранить
              {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {{'Подписки'}}
{% endblock %}
{% load thumbnail %}
{% block contend %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    {% include 'includes/switcher.html' %}     
    <h1>Ваши подписки:</h1>
    <article>
      {%if not page_obj %}
        <h2>Увы, вы пока не на кого не подписались...</h2>
      {% endif %}
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:'d E Y'}}
        </li>
        {% if post.group %}
        <li>
          Группа: {{ post.group}}
        </li>
        {% endif %}
      </ul>  
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}    
      <p>{{ post.text }}</p>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
    </article>
    {% if not foorloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества: {{ group.title }}</title>
{% endblock %}
{% load thumbnail %}
{% block contend %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
<div class="container py-5">
    <h1>{{group.title}}</h1>
    <p>
      {{group.description}}
    </p>
    <article>
      {% for i in page_obj %}
      <ul>
        <li>
          Автор: {{i.author.get_full_name}}
        </li>
        <li>
          Дата публикации: {{i.pub_date|date:'d E Y'}}
        </li>
      </ul>
      {% thumbnail i.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}         
      <p>
        {{i.text}}
      </p>
      {% if i.author == req_user %}
      <a href="{% url 'posts:edit' i.pk %}">\редактировать\</a>
      <a href="{% url 'posts:delite' i.pk %}">\удалить\</a>
      {% endif %}         
    </article>
    {% if not foorloop.last %}<hr>{% endif %}
    {% endfor %}
    <!-- под последним постом нет линии -->
    {% include 'includes/paginator.html' %}
  </div>  
{%endblock%}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {{'Главная страница проекта'|uglify}}
{% endblock %}
{% load cache %}
{% load thumbnail %}
{% block contend %}
  <div class="container py-5">
    {% include 'includes/switcher.html' %}     
    <h1>Последние обновления на сайте</h1>
    <article>
      {% cache 20 main %}
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:'d E Y'}}
        </li>
        {% if post.group %}
        <li>
          Группа: {{ post.group}}
        </li>
        {% endif %}
      </ul>  
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}    
      <p>{{ post.text }}</p>
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      {% if post.author == req_user %}
      <a href="{% url 'posts:edit' post.pk %}">\редактировать\</a>
      <a href="{% url 'posts:delite' post.pk %}">\удалить\</a>
      {% endif %}
    </article>
    {% if not foorloop.last %}<hr>{% endif %}
    {% endfor %}
    <!-- под последним постом нет линии -->
    {% endcache %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ post.text|truncatechars:30 }}
{% endblock %}
{% block contend %}
{% load thumbnail %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        {% if post.group %}
        <!-- если у поста есть группа -->
          <li class="list-group-item">
            Группа: {{post.group.title}}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span > {{ count }} </span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
       {{post.text}}
      </p>
      {% if post.author == req_user %}
      <a class="btn btn-primary" href={% url 'posts:edit' post.pk %}>
        редактировать запись
      </a>
      <a class="btn btn-primary" href="{% url 'posts:delite' post.pk %}">\удалить\</a>
      {% endif %}
      {% include 'includes/comments.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя: {{ user_author.get_full_name }}
{% endblock %}
{% load thumbnail %}
{% block contend %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ user_author.get_full_name }} </h1>
    <h3>Всего постов: {{ post_count }} </h3>
    <div class="mb-5">
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' user_author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' user_author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
    </div>
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ user_author.get_full_name }} <!--Лев Толстой-->
          <a href="{% url 'posts:profile' user_author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:'d E Y'}} <!-- 31 июля 1854 -->
        </li>
        {% if post.group %}
        <li>
          {{ post.group }}
        </li>
        {% endif %}
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
      {% if post.author == req_user %}
      <a href="{% url 'posts:edit' post.pk %}">\редактировать\</a>
      <a href="{% url 'posts:delite' post.pk %}">\удалить\</a>
      {% endif %}
    </article>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {%endif%}
    {% if not foorloop.last %}<hr>{% endif %}
    {% endfor %}
    <!-- под последним постом нет линии -->
    {% include 'includes/paginator.html' %}
    <!-- Здесь подключён паджинатор -->
  </div>
{% endblock %}